### PR TITLE
Test user endpoints

### PR DESCRIPTION
**Pull request by Nesmith-Charlesii**
User endpoint integration tests complete with modifications to how key/value pair data types are checked (i.e "joinedDate" and "_id fields". User routes reorganized to avoid clashes in url paths with dynamic parameters. User controller method "getUsers" updated to catch invalid "limit" params.

In the future, perhaps we should make one function in utils that converts specific properties in all collections to strings for checks against api responses. Api responses always return string values.

### CODE REVIEW

**Comment by dwight9339** [comment]
The tests look good. I agree that there's probably a much more elegant way to standardize how query params are handled in the future. Since many of our CRUD-focused endpoints have similar functionality I'm thinking it might be much better to take a more OOP approach and create a base class that handles the basic operations for all these endpoints in a uniform way and can be extended if need-be. However, for the time being there are only a couple things I think we should figure out before we get this merged:

1. It doesn't seem very useful to be able to specify a limit without also being able to specify an offset, right? Right now we can query a specific number of users off the top of the full list but we can't get a specified number of user entries from further down the list.
2. I noticed that the getUsers function checks for a valid value for limit and throws an error if the check fails. In my most recent PR I created a file called `/server/src/config/constants.ts` and specified a constant called DEFAULT_LIMIT. If the user passes an invalid value for limit or doesn't specify a limit at all, the default limit is used instead. I think this is approach is preferable as it offers a non-blocking solution. Either way, we should standardize on the handling of such things so as to avoid headaches down the line.

**Comment by Nesmith-Charlesii** [comment]
I think a base class would work well in this case. If we decide to go that route, I think that we should be consistent with the data types of certain fields in our models so that the base class can handle each operation with minimal type conversions, and so that our tests are more uniform in the future. For example, I believe that in the experience model, the `createdDate` field is of type `string`, and in the user model, the `joinedDate` is of type `Date`. The same pattern is followed in the interfaces of these two models. I didn't change the user model field types, so in the tests, what passed for experiences when comparing response data to db Data, didn't pass for similar user tests. I think it's appropriate to use a `Date` type for a date field, but if there's a reason for this difference, then no worries.

1. I had the same thought, but at the moment, I didn't see a clear reason to include an offset. I made this endpoint to pull a limited amount of users only with the means to keep from pulling all users in the case that we only need to display a certain amount of users for whatever reason, and to keep the API response time low (don't pull everyone, just a few). Down the line, we will probably add filters of some sort.

2.  Ok cool. I'll import it into the getUsers handler, replacing the default '0' with a more dynamic DEFAULT_LIMIT. I have that handled in this function here, where 0 is the default that would return all users if no limit is provided. 30 sounds a lot better lol:

```typescript
exports.getUsers = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const limit = req.query?.limit ? parseInt(req.query.limit as string, 10) : 0;
    const users = await utils.getUsers(limit)

    res.status(200).send(users);

  } catch(err) {
      console.log(err);
      next(err);
  }
}
``` 
I'll remove the block and push again. Thanks for the review!

**Comment by dwight9339** [comment]
Fair enough. Let's plan on making a base class for CRUD endpoint handlers and refactoring later on then.

**Review by dwight9339 — APPROVED** [review]

**Comment by Nesmith-Charlesii** [comment]
Perfect that sounds like a plan.

**Pull request merged**
